#! /bin/bash
# Work in progress. Will be done with FAKE and Paket.

function build-local()
{
nuget restore HealthKitServer.sln
xbuild /property:Configuration=Release HealthKitServer.Host/HealthKitServer.Host.csproj
xbuild /property:Configuration=Release TestHealthKitServer.HealthKitServer/TestHealthKitServer.HealthKitServer.csproj
xbuild /property:Configuration=Release TestHealthKitServer.Server/TestHealthKitServer.Server.csproj
}

function build-docker()
{
sudo docker build -t healthkitserver .
}

function run-local()
{
build-local
mono HealthKitServer.Host/bin/Release/HealthKitServer.Host.exe
}

function run-docker()
{
build-docker
sudo docker run -p 5002:5002 -it healthkitserver
}

function testdata-local(){
mono TestHealthRecordServer.Console/bin/Debug/TestHealthRecordServer.Console.exe $1
}

function unit-local(){
  mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe  TestHealthKitServer.HealthKitServer/bin/Release/Test*.dll -include=Unit
  mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe  TestHealthKitServer.Server/bin/Release/Test*.dll -include=Unit
}


function testdata-docker(){
sudo docker build -t healthkitservertestdataclient TestHealthRecordServer.Console/
sudo docker run -it -e URL=$1 healthkitservertestdataclient
}

"$@"
