#! /bin/bash

if [ -z "$(docker ps -a | grep healthkitserverdb)" ]
	then 
	    ./setUpDockerMysqlDatabase
            
	else 
               docker start healthkitserverdb 
fi
docker build -t healthkitserver ..
docker run -p 5002:5002 --link healthkitserverdb:healthkitserverdb -it healthkitserver 
